# Start from the latest golang base image
FROM golang:latest

# Add Maintainer Info
LABEL maintainer="baswvad <daviadbaswvad@gmail.com>"

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build . -o
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .


# Command to run the executable

