# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-Release-windows

on:
  workflow_dispatch:



jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2
      - name: Build for Windows
        run: |
          go mod init main
          go mod tidy
          GOOS=windows GOARCH=amd64 go build -o gotun2socks_windows_amd64.exe 
          GOOS=windows GOARCH=386 go build -o gotun2socks_windows_386.exe
     

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GOTUN2SOCKS_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Windows Binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GOTUN2SOCKS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gotun2socks_windows_amd64.exe
          asset_name: gotun2socks_windows_amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows Binaries (386)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GOTUN2SOCKS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gotun2socks_windows_386.exe
          asset_name: gotun2socks_windows_386.exe
          asset_content_type: application/octet-stream
